library(shinytest2)

test_that("{shinytest2} recording: board", {
  app <- AppDriver$new(name = "board", seed = 42, height = 1219, width = 1353)
  app$click("my_board-manage_blocks-add_block")
  app$click("my_board-manage_blocks-cancel_add")
  app$click("my_board-manage_blocks-confirm_add")
  app$set_inputs(`my_board-manage_blocks-registry_select` = "csv_block")
  app$set_inputs(`my_board-manage_blocks-block_id` = "qeayjdrzqoxgdye")
  app$set_inputs(`my_board-manage_blocks-registry_select` = "dataset_block")
  app$set_inputs(`my_board-manage_blocks-block_id` = "a")
  app$click("my_board-manage_blocks-confirm_add")
  app$set_inputs(`my_board-a-expr-dataset` = "BOD")
  app$click("my_board-manage_blocks-add_block")
  app$click("my_board-manage_blocks-confirm_add")
  app$set_inputs(`my_board-manage_blocks-registry_select` = "csv_block")
  app$set_inputs(`my_board-manage_blocks-block_id` = "ntzrociydemetbh")
  app$set_inputs(`my_board-manage_blocks-registry_select` = "dataset_block")
  app$set_inputs(`my_board-manage_blocks-block_id` = "b")
  app$click("my_board-manage_blocks-confirm_add")
  app$set_inputs(DataTables_Table_0_length = "5")
  app$set_inputs(`my_board-b-expr-dataset` = "BOD")
  app$set_inputs(`my_board-b-expr-dataset` = "ChickWeight")
  app$click("my_board-manage_blocks-add_block")
  app$click("my_board-manage_blocks-confirm_add")
  app$set_inputs(`my_board-manage_blocks-registry_select` = "csv_block")
  app$set_inputs(`my_board-manage_blocks-block_id` = "czajxkovzhddvrm")
  app$set_inputs(`my_board-manage_blocks-registry_select` = "merge_block")
  app$set_inputs(`my_board-manage_blocks-block_id` = "c")
  app$click("my_board-manage_blocks-confirm_add")
  app$set_inputs(DataTables_Table_2_length = "5")
  app$set_inputs(`my_board-c-expr-by` = character(0))
  app$set_inputs(`my_board-c-expr-type` = character(0))
  app$click("my_board-manage_links-links")
  app$click("my_board-manage_links-add_link")
  app$click("my_board-manage_links-rm_link")
  app$click("my_board-manage_links-cancel_links")
  app$click("my_board-manage_links-modify_links")
  app$click("my_board-manage_links-add_link")
  app$set_inputs(`my_board-manage_links-edbxrcxwquzrffb_from` = "")
  app$set_inputs(`my_board-manage_links-edbxrcxwquzrffb_to` = "")
  app$set_inputs(`my_board-manage_links-edbxrcxwquzrffb_input` = "")
  app$set_inputs(`my_board-manage_links-edbxrcxwquzrffb_from` = "a")
  app$set_inputs(`my_board-manage_links-edbxrcxwquzrffb_to` = "c")
  app$set_inputs(`my_board-manage_links-edbxrcxwquzrffb_input` = "x")
  app$click("my_board-manage_links-add_link")
  app$set_inputs(`my_board-manage_links-tcvubwfzjheaqgd_from` = "")
  app$set_inputs(`my_board-manage_links-tcvubwfzjheaqgd_to` = "")
  app$set_inputs(`my_board-manage_links-tcvubwfzjheaqgd_input` = "")
  app$set_inputs(`my_board-manage_links-tcvubwfzjheaqgd_from` = "b")
  app$set_inputs(`my_board-manage_links-tcvubwfzjheaqgd_to` = "c")
  app$set_inputs(`my_board-manage_links-tcvubwfzjheaqgd_input` = "y")
  app$click("my_board-manage_links-modify_links")
  app$set_inputs(`my_board-c-expr-by` = "Time")
  app$expect_values()
})


test_that("{shinytest2} recording: board1", {
  app <- AppDriver$new(name = "board1", seed = 42, height = 1219, width = 1353)
  app$click("my_board-manage_blocks-add_block")
  app$click("my_board-manage_blocks-cancel_add")
  app$click("my_board-manage_blocks-confirm_add")
  app$set_inputs(`my_board-manage_blocks-registry_select` = "csv_block")
  app$set_inputs(`my_board-manage_blocks-block_id` = "qeayjdrzqoxgdye")
  app$set_inputs(`my_board-manage_blocks-registry_select` = "dataset_block")
  app$set_inputs(`my_board-manage_blocks-block_id` = "a")
  app$click("my_board-manage_blocks-confirm_add")
  app$set_inputs(`my_board-a-expr-dataset` = "BOD")
  app$click("my_board-manage_blocks-add_block")
  app$click("my_board-manage_blocks-confirm_add")
  app$set_inputs(`my_board-manage_blocks-registry_select` = "csv_block")
  app$set_inputs(`my_board-manage_blocks-block_id` = "ntzrociydemetbh")
  app$set_inputs(`my_board-manage_blocks-registry_select` = "dataset_block")
  app$set_inputs(`my_board-manage_blocks-block_id` = "b")
  app$click("my_board-manage_blocks-confirm_add")
  app$set_inputs(DataTables_Table_0_length = "5")
  app$set_inputs(`my_board-b-expr-dataset` = "BOD")
  app$set_inputs(`my_board-b-expr-dataset` = "ChickWeight")
  app$click("my_board-manage_blocks-add_block")
  app$click("my_board-manage_blocks-confirm_add")
  app$set_inputs(`my_board-manage_blocks-registry_select` = "csv_block")
  app$set_inputs(`my_board-manage_blocks-block_id` = "czajxkovzhddvrm")
  app$set_inputs(`my_board-manage_blocks-registry_select` = "merge_block")
  app$set_inputs(`my_board-manage_blocks-block_id` = "c")
  app$click("my_board-manage_blocks-confirm_add")
  app$set_inputs(DataTables_Table_2_length = "5")
  app$set_inputs(`my_board-c-expr-by` = character(0))
  app$set_inputs(`my_board-c-expr-type` = character(0))
  app$expect_values()
  app$click("my_board-manage_links-links")
  app$click("my_board-manage_links-add_link")
  app$click("my_board-manage_links-rm_link")
  app$click("my_board-manage_links-cancel_links")
  app$click("my_board-manage_links-modify_links")
  app$click("my_board-manage_links-add_link")
  app$set_inputs(`my_board-manage_links-edbxrcxwquzrffb_from` = "")
  app$set_inputs(`my_board-manage_links-edbxrcxwquzrffb_to` = "")
  app$set_inputs(`my_board-manage_links-edbxrcxwquzrffb_input` = "")
  app$set_inputs(`my_board-manage_links-edbxrcxwquzrffb_id` = "edbxrcxwquzrffb")
  app$set_inputs(`my_board-manage_links-edbxrcxwquzrffb_from` = "a")
  app$set_inputs(`my_board-manage_links-edbxrcxwquzrffb_to` = "c")
  app$set_inputs(`my_board-manage_links-edbxrcxwquzrffb_input` = "x")
  app$set_inputs(`my_board-manage_links-edbxrcxwquzrffb_id` = "ac")
  app$set_inputs(`my_board-manage_links-ac_from` = "a")
  app$set_inputs(`my_board-manage_links-ac_to` = "c")
  app$set_inputs(`my_board-manage_links-ac_input` = "x")
  app$set_inputs(`my_board-manage_links-ac_id` = "ac")
  app$click("my_board-manage_links-add_link")
  app$set_inputs(`my_board-manage_links-tcvubwfzjheaqgd_from` = "")
  app$set_inputs(`my_board-manage_links-tcvubwfzjheaqgd_to` = "")
  app$set_inputs(`my_board-manage_links-tcvubwfzjheaqgd_input` = "")
  app$set_inputs(`my_board-manage_links-tcvubwfzjheaqgd_id` = "tcvubwfzjheaqgd")
  app$set_inputs(`my_board-manage_links-tcvubwfzjheaqgd_from` = "b")
  app$set_inputs(`my_board-manage_links-tcvubwfzjheaqgd_to` = "c")
  app$set_inputs(`my_board-manage_links-tcvubwfzjheaqgd_input` = "y")
  app$set_inputs(`my_board-manage_links-tcvubwfzjheaqgd_id` = "bc")
  app$set_inputs(`my_board-manage_links-bc_from` = "b")
  app$set_inputs(`my_board-manage_links-bc_to` = "c")
  app$set_inputs(`my_board-manage_links-bc_input` = "y")
  app$set_inputs(`my_board-manage_links-bc_id` = "bc")
  app$click("my_board-manage_links-modify_links")
  app$set_inputs(`my_board-c-expr-by` = "Time")
  app$expect_values()
})


test_that("{shinytest2} recording: board2", {
  app <- AppDriver$new(name = "board2", seed = 42, height = 1219, width = 1353)
  app$click("my_board-manage_blocks-add_block")
  app$click("my_board-manage_blocks-cancel_add")
  app$click("my_board-manage_blocks-confirm_add")
  app$set_inputs(`my_board-manage_blocks-registry_select` = "csv_block")
  app$set_inputs(`my_board-manage_blocks-block_id` = "qeayjdrzqoxgdye")
  app$set_inputs(`my_board-manage_blocks-block_id` = "a")
  app$set_inputs(`my_board-manage_blocks-registry_select` = "dataset_block")
  app$click("my_board-manage_blocks-confirm_add")
  app$set_inputs(`my_board-a-expr-dataset` = "BOD")
  app$click("my_board-manage_blocks-add_block")
  app$click("my_board-manage_blocks-confirm_add")
  app$set_inputs(`my_board-manage_blocks-registry_select` = "csv_block")
  app$set_inputs(`my_board-manage_blocks-block_id` = "ntzrociydemetbh")
  app$set_inputs(`my_board-manage_blocks-registry_select` = "dataset_block")
  app$set_inputs(`my_board-manage_blocks-block_id` = "b")
  app$click("my_board-manage_blocks-confirm_add")
  app$set_inputs(DataTables_Table_0_length = "5")
  app$set_inputs(`my_board-b-expr-dataset` = "BOD")
  app$set_inputs(`my_board-b-expr-dataset` = "ChickWeight")
  app$click("my_board-manage_blocks-add_block")
  app$click("my_board-manage_blocks-confirm_add")
  app$set_inputs(`my_board-manage_blocks-registry_select` = "csv_block")
  app$set_inputs(`my_board-manage_blocks-block_id` = "czajxkovzhddvrm")
  app$set_inputs(`my_board-manage_blocks-registry_select` = "merge_block")
  app$set_inputs(`my_board-manage_blocks-block_id` = "c")
  app$click("my_board-manage_blocks-confirm_add")
  app$set_inputs(DataTables_Table_2_length = "5")
  app$set_inputs(`my_board-c-expr-by` = character(0))
  app$set_inputs(`my_board-c-expr-type` = character(0))
  app$click("my_board-manage_links-links_mod")
  app$click("my_board-manage_links-add_link")
  app$click("my_board-manage_links-rm_link")
  app$click("my_board-manage_links-cancel_links")
  app$click("my_board-manage_links-modify_links")
  app$set_inputs(`my_board-manage_links-new_link_id` = "")
  app$set_inputs(`my_board-manage_links-new_link_id` = "ac")
  app$click("my_board-manage_links-add_link")
  app$set_inputs(`my_board-manage_links-ac_from` = "")
  app$set_inputs(`my_board-manage_links-ac_to` = "")
  app$set_inputs(`my_board-manage_links-ac_input` = "")
  app$set_inputs(`my_board-manage_links-ac_from` = "a")
  app$set_inputs(`my_board-manage_links-ac_to` = "c")
  app$set_inputs(`my_board-manage_links-ac_input` = "x")
  app$set_inputs(`my_board-manage_links-new_link_id` = "b")
  app$set_inputs(`my_board-manage_links-new_link_id` = "bc")
  app$click("my_board-manage_links-add_link")
  app$set_inputs(`my_board-manage_links-bc_from` = "")
  app$set_inputs(`my_board-manage_links-bc_to` = "")
  app$set_inputs(`my_board-manage_links-bc_input` = "")
  app$set_inputs(`my_board-manage_links-bc_from` = "b")
  app$set_inputs(`my_board-manage_links-bc_to` = "c")
  app$set_inputs(`my_board-manage_links-bc_input` = "y")
  app$click("my_board-manage_links-modify_links")
  app$set_inputs(`my_board-c-expr-by` = "Time")
  app$expect_values()
})
