library(shinytest2)

test_that("{shinytest2} recording: stack", {
  app <- AppDriver$new(variant = platform_variant(), name = "stack", seed = 42, height = 1219, 
      width = 1353)
  app$click("my_board-manage_stacks-stacks_mod")
  app$click("my_board-manage_stacks-add_stack")
  app$click("my_board-manage_stacks-rm_stack")
  app$click("my_board-manage_stacks-cancel_stacks")
  app$click("my_board-manage_stacks-modify_stacks")
  app$set_inputs(`my_board-manage_stacks-new_stack_id` = "")
  app$set_inputs(`my_board-manage_stacks-ac_blocks` = c("a", "c"))
  app$set_inputs(`my_board-manage_stacks-ac_name` = "Stack 1")
  app$set_inputs(`my_board-manage_stacks-ac_blocks` = c("a", "c", "b"))
  app$click("my_board-manage_stacks-modify_stacks")
  app$set_window_size(width = 1353, height = 1219)
  app$expect_screenshot()
  app$expect_values()
  app$set_window_size(width = 1353, height = 1219)
  app$set_inputs(`my_board-ac-stack_name_in` = "abc")
  app$expect_values()
  app$set_window_size(width = 1353, height = 1219)
  app$click("my_board-ac-rm_stack")
  app$set_window_size(width = 1353, height = 1219)
  app$expect_values()
  app$click("my_board-manage_stacks-stacks_mod")
  app$click("my_board-manage_stacks-modify_stacks")
  app$set_inputs(`my_board-manage_stacks-new_stack_id` = "abc")
  app$click("my_board-manage_stacks-add_stack")
  app$set_inputs(`my_board-manage_stacks-abc_blocks` = character(0))
  app$set_inputs(`my_board-manage_stacks-abc_name` = "Stack 4")
  app$set_inputs(`my_board-manage_stacks-abc_name` = "ABC")
  app$set_inputs(`my_board-manage_stacks-abc_blocks` = "a")
  app$set_inputs(`my_board-manage_stacks-abc_blocks` = c("a", "b"))
  app$set_inputs(`my_board-manage_stacks-abc_blocks` = c("a", "b", "c"))
  app$click("my_board-manage_stacks-modify_stacks")
  app$click("my_board-abc-rm_stack")
  app$set_inputs(`my_board-abc-stack_name_in` = "ABC")
  app$set_window_size(width = 1353, height = 1219)
  app$expect_values()
})
